image: node:16.16.0

stages:
  - test

test:
  image: node:latest
  stage: test
  only:
    refs:
      - merge_request
      - master
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npm run e2e